# Generated by Django 5.0 on 2023-12-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=128)),
                ('task_description', models.CharField(max_length=256)),
            ],
        ),
    ]
