# Generated by Django 5.0 on 2023-12-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motor_id', models.IntegerField()),
                ('motor_speed', models.FloatField()),
            ],
        ),
    ]
