# Generated by Django 5.0 on 2023-12-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_motorcontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcontrol',
            name='motor_id',
            field=models.FloatField(),
        ),
    ]
