# Generated by Django 5.0 on 2023-12-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_delete_motorcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motor_name', models.CharField(max_length=128)),
                ('motor_speed', models.IntegerField()),
            ],
        ),
    ]
