# Generated by Django 5.0 on 2023-12-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_motorcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128)),
                ('nick_name', models.CharField(max_length=128)),
                ('register_time', models.DateTimeField()),
            ],
        ),
    ]
