# Generated by Django 5.0 on 2023-12-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nick_name',
            new_name='username',
        ),
    ]
