# Generated by Django 5.0 on 2023-12-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_user_last_login_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
    ]
