# Generated by Django 5.0 on 2023-12-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_loginrecord_remove_user_last_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrecord',
            name='token',
            field=models.CharField(default='a', max_length=128),
        ),
    ]
