# Generated by Django 5.0 on 2023-12-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_loginrecord_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrecord',
            name='token',
            field=models.CharField(max_length=128),
        ),
    ]
