# Generated by Django 5.0 on 2023-12-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_alter_loginrecord_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
