# Generated by Django 5.0 on 2023-12-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0020_motor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spinning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motor_name', models.CharField(max_length=128)),
                ('scheduled_time', models.DateTimeField()),
                ('motor_speed', models.IntegerField()),
                ('duration_sec', models.IntegerField()),
            ],
        ),
    ]
