# Generated by Django 5.0 on 2024-01-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0022_motorcontrol_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcontrol',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
