# Generated by Django 5.0 on 2024-07-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0023_alter_motorcontrol_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEventRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.IntegerField(choices=[(1, 'ESP32S3_1'), (2, 'ESP32S3_2'), (3, 'ESP32S3_3'), (4, 'ESP32S3_4'), (5, 'Robo_Arm')], default=1)),
                ('event_type', models.IntegerField(choices=[(1, 'Motor'), (2, 'Robot_Arm')], default=1)),
                ('statue', models.IntegerField(choices=[(1, 'Active'), (2, 'Done')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MotorEventRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('motor_id', models.IntegerField(choices=[(1, 'Motor_0'), (2, 'Motor_1'), (3, 'Motor_2'), (4, 'Motor_3')], default=1)),
                ('data_type', models.IntegerField(choices=[(1, 'PCNT'), (2, 'PWM')], default=1)),
                ('data', models.IntegerField()),
                ('parent_event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.deviceeventrecord')),
            ],
        ),
    ]
